### ISSUE TITLE
feat: Add functionality for item templates in add part

### ISSUE THREAD

**Issue by eikib** [OptiCorp/inventory-app#214]
A user should be able be able to choose an item template at a new step before submitting an item. If the user chooses to not use an existing template, they need to input all the fields themself. When submitting an item without choosing an existing template, they should also submit this as a new template. If they choose an existing template, the item template fields should be locked (or if you edit them, the user is told that this will be a new template).

- [ ] Add new step to pick an existing template or not (show the templates as cards)
- [ ] Insert item template values into input fields
- [ ] Submitting an item without existing template should first create the template

**Comment by Benjamin-Lyon** [comment]
@Kodehodekatty if you manually move a card to `Done` it means that you haven't assigned it to a pull request. If you do manually move it anyway, remember to close it 😺
