### ISSUE TITLE
feat: add font styles in accordance to Figma designs

### ISSUE THREAD

**Issue by Benjamin-Lyon** [OptiCorp/inventory-app#223]
font sizes and weight are currently set in individual styled components. it would be better to create a `FONT_STYLES` const in `GlobalStyles.ts` that organizes all the various fonts we use in this project.

**Comment by Kodehodekatty** [comment]
is there more then the Archivo font? in figma its just that one unless i've missed some

**Comment by Kodehodekatty** [comment]
but i believe the font family style still applies to all text in the project unless specified otherwise unless im mistaken?
```
const GlobalStyles = createGlobalStyle<Props>`
   body, :root, html {
        margin: 0;
        width: 100%;
      
        font-family: 'Archivo', sans-serif;
        font-size: 1rem;
        background-color: ${COLORS.secondary};
    }
```
